apiVersion: v1
kind: Service
metadata:
  name: defectdojo-redis
  namespace: cxado-aspm
  labels:
    app: defectdojo-redis
spec:
  selector:
    app: defectdojo-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: defectdojo-redis
  namespace: cxado-aspm
  labels:
    app: defectdojo-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: defectdojo-redis
  template:
    metadata:
      labels:
        app: defectdojo-redis
    spec:
      enableServiceLinks: false
      imagePullSecrets:
        - name: nexus-registry
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: redis
          image: nexus.svo.aero:8345/cxado-docker/redis:7
          imagePullPolicy: IfNotPresent
          args:
            - redis-server
            - "--save"
            - ""
            - "--appendonly"
            - "no"
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            periodSeconds: 10
