#!/usr/bin/env bash
# Rsync ui-minimal static site to k3s node and generate config.js.
#
#   ./scripts/k8s/k3s-offline-bundle-ui-minimal.sh
#   ./scripts/k8s/k3s-offline-bundle-ui-minimal.sh --remote
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
# shellcheck source=scripts/k8s/cxado-offline-env.sh
source "${ROOT}/scripts/k8s/cxado-offline-env.sh"
SRC="${ROOT}/projects/egregore/ui-minimal"
DEST="${CXADO_UI_MINIMAL_DEST:-/home/bbv/cxado/ui-minimal}"
NODE_IP="${CXADO_NODE_IP:-192.168.0.133}"
CORP_IP="${CXADO_NODE_HOSTNAME_IP:-10.8.185.15}"

SSH_HOST="${CXADO_OFFLINE_SSH_HOST}"
SSH_PORT="${CXADO_OFFLINE_SSH_PORT}"
REMOTE=0

for arg in "$@"; do
  case "$arg" in
    --dest=*) DEST="${arg#*=}" ;;
    --remote) REMOTE=1 ;;
  esac
done

[[ -f "${SRC}/index.html" ]] || { echo "missing ${SRC}/index.html" >&2; exit 1; }

write_config_js() {
  local target="$1"
  cat >"${target}/config.js" <<'EOF'
// Generated by k3s-offline-bundle-ui-minimal.sh — do not edit on node.
window.EGREGORE_DEFAULTS = (function () {
  const host = window.location.hostname || "127.0.0.1";
  const proto = window.location.protocol === "http:" ? "http:" : "https:";
  const origin = window.location.origin || proto + "//" + host + ":30300";
  return {
    api: origin,
    langfuse: proto + "//" + host + ":30001",
    langfuseProject: "egregore-dev",
  };
})();
EOF
  chmod a+r "${target}/config.js"
}

rsync_site() {
  local target="$1"
  echo "[ui-minimal] rsync ${SRC}/ -> ${target}/"
  mkdir -p "${target}"
  rsync -av --delete --info=progress2 \
    --exclude 'config.js' \
    "${SRC}/" "${target}/"
  write_config_js "${target}"
  chmod -R a+rX "${target}"
  echo "[ui-minimal] done ($(du -sh "${target}" | cut -f1))"
}

if [[ "${REMOTE}" -eq 1 ]]; then
  ssh -p "${SSH_PORT}" "${SSH_HOST}" "mkdir -p '${DEST}'"
  rsync -av --delete --info=progress2 \
    --exclude 'config.js' \
    -e "ssh -p ${SSH_PORT}" \
    "${SRC}/" "${SSH_HOST}:${DEST}/"
  ssh -p "${SSH_PORT}" "${SSH_HOST}" "cat >'${DEST}/config.js'" <<'EOF'
// Generated by k3s-offline-bundle-ui-minimal.sh — do not edit on node.
window.EGREGORE_DEFAULTS = (function () {
  const host = window.location.hostname || "127.0.0.1";
  const proto = window.location.protocol === "http:" ? "http:" : "https:";
  const origin = window.location.origin || proto + "//" + host + ":30300";
  return {
    api: origin,
    langfuse: proto + "//" + host + ":30001",
    langfuseProject: "egregore-dev",
  };
})();
EOF
  ssh -p "${SSH_PORT}" "${SSH_HOST}" "chmod -R a+rX '${DEST}' && test -f '${DEST}/index.html' && test -f '${DEST}/config.js'"
else
  rsync_site "${DEST}"
fi
