#!/usr/bin/env bash
# Pull k3s secrets and regenerate docs/architecture-site/js/credentials.js
#
# Usage:
#   ./scripts/k8s/k3s-sync-arch-docs-credentials.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
# shellcheck source=scripts/k8s/cxado-offline-env.sh
source "${ROOT}/scripts/k8s/cxado-offline-env.sh"
OUT="${ROOT}/docs/architecture-site/js/credentials.js"
SSH_HOST="${CXADO_OFFLINE_SSH_HOST}"
SSH_PORT="${CXADO_OFFLINE_SSH_PORT}"
KCTL="KUBECONFIG=/home/bbv/.kube/config k3s kubectl"

decode_secret() {
  local ns="$1" name="$2" key="$3"
  ssh -p "${SSH_PORT}" "${SSH_HOST}" \
    "${KCTL} get secret -n ${ns} ${name} -o jsonpath='{.data.${key}}'" \
    | python3 -c "import sys,base64; print(base64.b64decode(sys.stdin.read()).decode())"
}

log() { printf '[sync-creds] %s\n' "$*"; }

log "fetching secrets from ${SSH_HOST}..."

GRAFANA_ADMIN="$(decode_secret cxado-obs grafana-auth admin_password)"
GRAFANA_VIEWER_USER="$(decode_secret cxado-obs grafana-auth viewer_username)"
GRAFANA_VIEWER_PW="$(decode_secret cxado-obs grafana-auth viewer_password)"
PG_PW="$(decode_secret cxado-data cxado-credentials postgres-password)"
REDIS_PW="$(decode_secret cxado-data cxado-credentials redis-password)"
NEO4J_PW="$(decode_secret cxado-data cxado-credentials neo4j-password)"
LF_PG="$(decode_secret cxado-langfuse langfuse-secrets postgres-password)"
LF_REDIS="$(decode_secret cxado-langfuse langfuse-secrets redis-auth)"
LF_CH="$(decode_secret cxado-langfuse langfuse-secrets clickhouse-password)"
LF_MINIO_USER="$(decode_secret cxado-langfuse langfuse-secrets minio-root-user)"
LF_MINIO_PW="$(decode_secret cxado-langfuse langfuse-secrets minio-root-password)"

DATE="$(date +%Y-%m-%d)"

cat >"${OUT}" <<EOF
/** Auto-generated by k3s-sync-arch-docs-credentials.sh — TEST LAB ONLY */
window.CXADO_CREDENTIALS = {
  warning: "Тестовый стенд · не использовать в production",
  updated: "${DATE}",
  entries: [
    { service: "Grafana", port: 30002, auth: "Basic", rows: [
      { role: "Admin", user: "admin", password: "${GRAFANA_ADMIN}" },
      { role: "Viewer", user: "${GRAFANA_VIEWER_USER}", password: "${GRAFANA_VIEWER_PW}" },
    ]},
    { service: "Langfuse UI", port: 30001, auth: "Email", rows: [
      { role: "Dev Admin", user: "dev@egregore.local", password: "egregore-dev" },
    ], notes: ["Project: egregore-dev", "Public key: pk-lf-egregore-dev-local", "Secret key: sk-lf-egregore-dev-local"] },
    { service: "Neo4j Browser", port: 30474, auth: "Database", rows: [
      { role: "neo4j", user: "neo4j", password: "${NEO4J_PW}" },
    ]},
    { service: "Postgres (egregore)", port: 5432, auth: "ClusterIP", rows: [
      { role: "postgres", user: "postgres", password: "${PG_PW}" },
    ], notes: ["Host: postgres.cxado-data.svc.cluster.local", "Database: egregore"] },
    { service: "Redis (egregore)", port: 6379, auth: "ClusterIP", rows: [
      { role: "—", user: "—", password: "${REDIS_PW}" },
    ]},
    { service: "Langfuse Postgres", port: 5432, auth: "ClusterIP", rows: [
      { role: "langfuse", user: "langfuse", password: "${LF_PG}" },
    ]},
    { service: "Langfuse Redis", port: 6379, auth: "ClusterIP", rows: [
      { role: "—", user: "—", password: "${LF_REDIS}" },
    ]},
    { service: "Langfuse ClickHouse", port: 8123, auth: "ClusterIP", rows: [
      { role: "clickhouse", user: "clickhouse", password: "${LF_CH}" },
    ]},
    { service: "Langfuse MinIO", port: 9000, auth: "S3", rows: [
      { role: "root", user: "${LF_MINIO_USER}", password: "${LF_MINIO_PW}" },
    ]},
    { service: "Egregore API / UI", port: 30300, auth: "None", rows: [
      { role: "—", user: "—", password: "AUTH_ENABLED=false" },
    ]},
    { service: "Veil API / MCP", port: 30990, auth: "None", rows: [
      { role: "—", user: "—", password: "Keycloak off" },
    ]},
    { service: "Prometheus", port: 30091, auth: "None", rows: [
      { role: "—", user: "—", password: "—" },
    ]},
  ],
};
EOF

log "wrote ${OUT}"
