#!/usr/bin/env bash
# Generate Langfuse secrets for offline k3s and write env file (gitignored).
#
# Usage:
#   ./scripts/k8s/langfuse-create-secrets.sh
#
# Env:
#   CXADO_NODE_IP (default: 10.8.185.15) — used for NEXTAUTH_URL
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
# shellcheck source=scripts/k8s/cxado-offline-env.sh
source "${ROOT}/scripts/k8s/cxado-offline-env.sh"
OUT="${LANGFUSE_SECRETS_ENV_FILE:-${ROOT}/deploy/.secrets/langfuse-k3s.env}"
NODE_IP="${CXADO_NODE_IP}"
LANGFUSE_NODEPORT="${LANGFUSE_NODEPORT:-30001}"

rand_b64() { openssl rand -base64 32 | tr -d '\n'; }
rand_hex32() { openssl rand -hex 32; }

POSTGRES_PASSWORD="$(rand_b64 | tr '+/' '-_' | tr -d '=')"
REDIS_AUTH="$(rand_b64 | tr '+/' '-_' | tr -d '=')"
CLICKHOUSE_PASSWORD="$(rand_b64 | tr '+/' '-_' | tr -d '=')"
MINIO_ROOT_USER="minio"
MINIO_ROOT_PASSWORD="$(rand_b64 | tr '+/' '-_' | tr -d '=')"
NEXTAUTH_SECRET="$(rand_b64)"
SALT="$(rand_b64)"
ENCRYPTION_KEY="$(rand_hex32)"
NEXTAUTH_URL="https://${NODE_IP}:${LANGFUSE_NODEPORT}"

# URL-encode password for DATABASE_URL (minimal: only common specials)
urlencode() {
  python3 -c 'import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1], safe=""))' "$1"
}
PG_ENC="$(urlencode "${POSTGRES_PASSWORD}")"
DATABASE_URL="postgresql://langfuse:${PG_ENC}@postgres.cxado-langfuse.svc.cluster.local:5432/langfuse"

mkdir -p "$(dirname "${OUT}")"
cat >"${OUT}" <<EOF
# generated by scripts/k8s/langfuse-create-secrets.sh (do not commit)
LANGFUSE_NEXTAUTH_URL=${NEXTAUTH_URL}
LANGFUSE_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
LANGFUSE_REDIS_AUTH=${REDIS_AUTH}
LANGFUSE_CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
LANGFUSE_MINIO_ROOT_USER=${MINIO_ROOT_USER}
LANGFUSE_MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
LANGFUSE_NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
LANGFUSE_SALT=${SALT}
LANGFUSE_ENCRYPTION_KEY=${ENCRYPTION_KEY}
LANGFUSE_DATABASE_URL=${DATABASE_URL}
EOF
chmod 600 "${OUT}"
echo "wrote ${OUT}"
