apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redpanda-data
  namespace: cxado-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: cxado-data
spec:
  selector:
    app: redpanda
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
  namespace: cxado-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      enableServiceLinks: false
      containers:
        - name: redpanda
          image: docker.redpanda.com/redpandadata/redpanda:v24.2.4
          imagePullPolicy: IfNotPresent
          args:
            - redpanda
            - start
            - --kafka-addr
            - internal://0.0.0.0:9092,external://0.0.0.0:19092
            - --advertise-kafka-addr
            - internal://redpanda.cxado-data.svc.cluster.local:9092,external://localhost:19092
            - --mode
            - dev-container
            - --smp
            - "1"
            - --memory
            - 1G
            - --reserve-memory
            - 0M
            - --overprovisioned
          ports:
            - containerPort: 9092
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1536Mi
              cpu: "2"
          volumeMounts:
            - name: data
              mountPath: /var/lib/redpanda/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redpanda-data
