// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: auth_broker/v1/token.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audience      string                 `protobuf:"bytes,1,opt,name=audience,proto3" json:"audience,omitempty"`
	Scopes        []string               `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessTokenRequest) Reset() {
	*x = GetAccessTokenRequest{}
	mi := &file_auth_broker_v1_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessTokenRequest) ProtoMessage() {}

func (x *GetAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_broker_v1_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*GetAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_broker_v1_token_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccessTokenRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *GetAccessTokenRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type GetAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	TokenType     string                 `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessTokenResponse) Reset() {
	*x = GetAccessTokenResponse{}
	mi := &file_auth_broker_v1_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessTokenResponse) ProtoMessage() {}

func (x *GetAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_broker_v1_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*GetAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_broker_v1_token_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccessTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetAccessTokenResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *GetAccessTokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

var File_auth_broker_v1_token_proto protoreflect.FileDescriptor

const file_auth_broker_v1_token_proto_rawDesc = "" +
	"\n" +
	"\x1aauth_broker/v1/token.proto\x12\x0eauth_broker.v1\"K\n" +
	"\x15GetAccessTokenRequest\x12\x1a\n" +
	"\baudience\x18\x01 \x01(\tR\baudience\x12\x16\n" +
	"\x06scopes\x18\x02 \x03(\tR\x06scopes\"y\n" +
	"\x16GetAccessTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x05R\texpiresIn\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType2o\n" +
	"\fTokenService\x12_\n" +
	"\x0eGetAccessToken\x12%.auth_broker.v1.GetAccessTokenRequest\x1a&.auth_broker.v1.GetAccessTokenResponseBTZRgithub.com/butbeautifulv/cxado/shared/go/auth-broker/internal/transport/grpc/pb;pbb\x06proto3"

var (
	file_auth_broker_v1_token_proto_rawDescOnce sync.Once
	file_auth_broker_v1_token_proto_rawDescData []byte
)

func file_auth_broker_v1_token_proto_rawDescGZIP() []byte {
	file_auth_broker_v1_token_proto_rawDescOnce.Do(func() {
		file_auth_broker_v1_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_broker_v1_token_proto_rawDesc), len(file_auth_broker_v1_token_proto_rawDesc)))
	})
	return file_auth_broker_v1_token_proto_rawDescData
}

var file_auth_broker_v1_token_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_broker_v1_token_proto_goTypes = []any{
	(*GetAccessTokenRequest)(nil),  // 0: auth_broker.v1.GetAccessTokenRequest
	(*GetAccessTokenResponse)(nil), // 1: auth_broker.v1.GetAccessTokenResponse
}
var file_auth_broker_v1_token_proto_depIdxs = []int32{
	0, // 0: auth_broker.v1.TokenService.GetAccessToken:input_type -> auth_broker.v1.GetAccessTokenRequest
	1, // 1: auth_broker.v1.TokenService.GetAccessToken:output_type -> auth_broker.v1.GetAccessTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_broker_v1_token_proto_init() }
func file_auth_broker_v1_token_proto_init() {
	if File_auth_broker_v1_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_broker_v1_token_proto_rawDesc), len(file_auth_broker_v1_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_broker_v1_token_proto_goTypes,
		DependencyIndexes: file_auth_broker_v1_token_proto_depIdxs,
		MessageInfos:      file_auth_broker_v1_token_proto_msgTypes,
	}.Build()
	File_auth_broker_v1_token_proto = out.File
	file_auth_broker_v1_token_proto_goTypes = nil
	file_auth_broker_v1_token_proto_depIdxs = nil
}
